import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./components/Navbar";
import { HeroSection } from "./components/HeroSection";
import { Footer } from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 const links=[
    {
      link: "/about",
      label: "Features",
    },
    {
      link: "/pricing",
      label: "Pricing",
    },
    {
      link: "/learn",
      label: "Learn",
    },
    {
      link: "/community",
      label: "Community",
    }
  ];

export default function RootLayout({ children }: { children: React.ReactNode }) {
 

  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-between ">
        <Navbar links={links} />
      
        {children}
        <Footer/>
      </body>
    </html>
  );
}
